(()=>{'use strict';
const $=id=>document.getElementById(id),clean=v=>String(v??'').trim().replace(/\s+/g,' '),norm=v=>clean(v).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=v=>{v=parseFloat(String(v??'').replace(',','.'));return Number.isFinite(v)?v:null};
const S={venues:[],events:[],providers:null,byId:new Map,cities:[],byCity:new Map,selected:{from:null,to:null},routes:[],curated:false};
const alias=v=>S.providers?.aliases?.[clean(v)]||clean(v),key=(city,country)=>`${norm(city)}|${norm(alias(country))}`,tokens=v=>(Array.isArray(v)?v:clean(v).split(/[;|]+/)).map(clean).filter(Boolean),coords=r=>{const lat=num(r?.Latitude??r?.Event_Latitude??r?.Venue_Latitude),lng=num(r?.Longitude??r?.Event_Longitude??r?.Venue_Longitude);return lat===null||lng===null?null:{lat,lng}},live=r=>!['hold','flag','closed','removed','inactive','cancelled'].includes(norm(r?.Status)),date=v=>{const m=clean(v).match(/^(\d{4})-(\d{2})-(\d{2})/);return m?new Date(+m[1],+m[2]-1,+m[3]):null},day=v=>{const d=new Date(v);d.setHours(0,0,0,0);return d};
function eventLoc(e){const v=S.byId.get(clean(e.Venue_ID));return{city:tokens(e.City||e.Event_City||e.Venue_City||v?.City)[0]||'',country:alias(e.Country||e.Event_Country||e.Venue_Country||v?.Country),xy:coords(e)||coords(v)}}
function buildCities(){const m=new Map,add=(city,country,xy,type)=>{city=clean(city);country=alias(country);if(!city)return;const k=key(city,country);if(!m.has(k))m.set(k,{key:k,city,country,venueCount:0,eventCount:0,latSum:0,lngSum:0,n:0});const x=m.get(k);x[type+'Count']++;if(xy){x.latSum+=xy.lat;x.lngSum+=xy.lng;x.n++}};S.venues.filter(live).forEach(v=>tokens(v.City).forEach((city,i)=>add(city,v.Country,i?null:coords(v),'venue')));S.events.filter(live).forEach(e=>{const l=eventLoc(e);add(l.city,l.country,l.xy,'event')});S.cities=[...m.values()].map(x=>({...x,label:x.country?`${x.city}, ${x.country}`:x.city,search:norm(`${x.city} ${x.country}`),lat:x.n?x.latSum/x.n:null,lng:x.n?x.lngSum/x.n:null,total:x.venueCount+x.eventCount})).sort((a,b)=>a.city.localeCompare(b.city)||a.country.localeCompare(b.country));S.byCity=new Map(S.cities.map(x=>[x.key,x]))}
const config=country=>S.providers.countries[alias(country)]||{hubs:[],rail:[],coach:[],ferry:[],air:[],notes:'No dedicated provider entry has been added yet.'};
function providerMap(){const m=new Map,add=p=>p?.name&&!m.has(norm(p.name))&&m.set(norm(p.name),p);Object.values(S.providers.globals).flat().forEach(add);Object.values(S.providers.countries).forEach(c=>['rail','coach','ferry','air'].forEach(k=>(c[k]||[]).forEach(add)));return m}
const getProvider=name=>providerMap().get(norm(name))||{name,url:`https://www.google.com/search?q=${encodeURIComponent(name+' official booking')}`,label:'Search official provider'},uniq=list=>{const m=new Map;list.filter(Boolean).forEach(x=>{x=typeof x==='string'?getProvider(x):x;if(x?.name&&!m.has(norm(x.name)))m.set(norm(x.name),x)});return[...m.values()]};
function km(a,b){if(![a.lat,a.lng,b.lat,b.lng].every(Number.isFinite))return null;const r=v=>v*Math.PI/180,dlat=r(b.lat-a.lat),dlng=r(b.lng-a.lng),h=Math.sin(dlat/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dlng/2)**2;return Math.round(6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h)))}
const routeKey=(a,b)=>`${norm(a.city)}|${norm(b.city)}`;
function curated(a,b){const direct=S.providers.majorRoutes[routeKey(a,b)];if(direct)return direct.map(x=>({...x,curated:true}));const reverse=S.providers.majorRoutes[routeKey(b,a)];return reverse?reverse.map(x=>({...x,path:[...x.path].reverse(),curated:true})):null}
function path(a,b,mode){const ca=config(a.country),cb=config(b.country),out=[a.city],add=x=>x&&norm(out.at(-1))!==norm(x)&&norm(x)!==norm(b.city)&&out.push(x);if(norm(a.country)!==norm(b.country)){const ha=ca.hubs.find(x=>norm(x)!==norm(a.city)),hb=cb.hubs.find(x=>norm(x)!==norm(b.city));if(mode==='rail'){a.total<8&&add(ha);b.total<8&&add(hb)}else{a.total<4&&add(ha);b.total<4&&add(hb)}}else if(a.total<3||b.total<3)add(ca.hubs.find(x=>![norm(a.city),norm(b.city)].includes(norm(x))));out.push(b.city);return[...new Set(out)]}
function estimate(mode,d,changes){if(!d)return'Check provider';let h=mode==='Rail'?d/115+.75:mode==='Coach'?d/75+1:mode==='Flight'?d/700+3.3:d/42+1.5;h+=changes*.75;const lo=Math.max(1,Math.floor(h)),hi=Math.max(lo+1,Math.ceil(h+Math.max(1,h*.15)));return`Approx. ${lo}–${hi} h`}
function generic(a,b){const ca=config(a.country),cb=config(b.country),g=S.providers.globals,d=km(a,b),same=norm(a.country)===norm(b.country),out=[],make=(mode,icon,pth,changes,providers,note,recommended=false)=>out.push({mode,icon,path:pth,changes,direct:changes?'check':'check',estimate:estimate(mode,d,changes),providers:uniq(providers).map(x=>x.name),note,curated:false,recommended});const rail=uniq([...(ca.rail||[]),...(same?[]:cb.rail||[]),...(g.rail||[])]);if((ca.rail.length||cb.rail.length)&&![a.country,b.country].some(x=>['Malta','Iceland','Cyprus'].includes(x))){const p=path(a,b,'rail');make('Rail','train',p,Math.max(0,p.length-2),rail,'Check direct trains first. For smaller cities, compare the national operators and the suggested interchange hubs.',d?d<=900:true)}const coach=uniq([...(ca.coach||[]),...(same?[]:cb.coach||[]),...(g.coach||[])]);if(coach.length){const p=path(a,b,'coach');make('Coach','bus',p,Math.max(0,p.length-2),coach,'Search direct coaches first. Smaller destinations may need a change at the nearest regional hub.',!out.length||(d&&d<550))}if((ca.ferry.length||cb.ferry.length)&&!same)out.push({mode:'Ferry + surface',icon:'ferry',path:[a.city,'relevant ferry port',b.city],changes:2,direct:false,estimate:'Check sailing and connections',providers:uniq([...(ca.ferry||[]),...(cb.ferry||[]),...(g.ferry||[])]).map(x=>x.name),note:'Ferry availability is route- and season-specific. Confirm the sailing before arranging surface connections.',curated:false,recommended:false});if(!same||!d||d>300||[a.country,b.country].some(x=>['Malta','Iceland','Cyprus','Taiwan','United States','Canada','South Africa','Australia','New Zealand'].includes(x)))make('Flight','flight',[`${a.city} area airport`,`${b.city} area airport`],0,[...(ca.air||[]),...(same?[]:cb.air||[]),...(g.flight||[])],'Search the whole metropolitan area where possible and compare airport transfers.',d?d>1000:false);out.push({mode:'Route overview',icon:'overview',path:[a.city,b.city],changes:0,direct:'check',estimate:'Compare all modes',providers:(g.overview||[]).map(x=>x.name),note:'Use this as a broad cross-check, then book with the official operator where possible.',curated:false,recommended:false});if(!out.some(x=>x.recommended)&&out[0])out[0].recommended=true;return out}
function options(a,b){const x=curated(a,b);S.curated=!!x;return(x||generic(a,b)).map((r,i)=>({...r,recommended:r.recommended??i===0,changesValue:typeof r.changes==='number'?r.changes:parseInt(r.changes)||9}))}
function eventCount(city,value){const from=day(value),to=new Date(from);to.setDate(to.getDate()+6);return S.events.filter(live).filter(e=>{const l=eventLoc(e),d=date(e.Event_Date);return key(l.city,l.country)===city.key&&d&&d>=from&&d<=to}).length}
const links=names=>uniq(names.map(getProvider)).map(p=>`<a href="${esc(p.url)}" target="_blank" rel="noopener">${esc(p.name)} ↗</a>`).join(''),icon=x=>x==='train'?`<img src="train.webp" alt="" onerror="this.replaceWith(document.createTextNode('🚄'))">`:({bus:'🚌',flight:'✈️',ferry:'⛴️',overview:'🧭'}[x]||'🧭'),badge=r=>r.direct===true?'<span class="badge">Known direct option</span>':r.direct===false?'<span class="badge secondary">Connection required</span>':'<span class="badge secondary">Check direct service</span>';
function renderRoutes(){const order={Rail:1,Coach:2,'Ferry + surface':3,Flight:4,'Route overview':5},sort=$('sort').value,r=[...S.routes];sort==='mode'&&r.sort((a,b)=>(order[a.mode]||9)-(order[b.mode]||9));sort==='changes'&&r.sort((a,b)=>a.changesValue-b.changesValue);sort==='recommended'&&r.sort((a,b)=>+!!b.recommended-+!!a.recommended);$('routes').innerHTML=r.map(x=>`<article class="route ${x.recommended?'recommended':''}"><div class="route-top"><div class="mode"><div class="mode-pic">${icon(x.icon)}</div><div><strong>${esc(x.mode)}</strong><small>${x.curated?'Curated main-city guide':'Provider-based suggestion'}</small></div></div><div class="path"><strong>${x.path.map(esc).join(' → ')}</strong><small>${esc(x.changes)} suggested change${String(x.changes)==='1'?'':'s'}</small></div><div class="estimate"><strong>${esc(x.estimate)}</strong>${badge(x)}</div></div><div class="route-bottom"><div class="providers">${links(x.providers||[])}</div><div class="route-note">${esc(x.note)}</div></div></article>`).join('')||'<div class="empty">No provider guidance is available yet.</div>'}
function renderDirectory(a,b){const groups=[],seen=new Set;[a,b].forEach(city=>{const c=config(city.country);[['Rail',c.rail],['Coach / bus',c.coach],['Ferry',c.ferry],['Air',c.air]].forEach(([title,items])=>{const k=city.country+'|'+title;if(items.length&&!seen.has(k)){seen.add(k);groups.push({country:city.country,title,items})}})});groups.push({country:'General comparison',title:'Cross-border search',items:uniq([...S.providers.globals.rail,...S.providers.globals.coach,...S.providers.globals.flight,...S.providers.globals.overview])});$('provider-directory-intro').textContent=`Official and regional sources relevant to ${a.country||a.city} and ${b.country||b.city}. Local operators appear before comparison sites.`;$('provider-columns').innerHTML=groups.map(g=>`<section class="provider-group"><h4>${esc(g.country)} · ${esc(g.title)}</h4>${uniq(g.items).map(p=>`<a class="provider-link" href="${esc(p.url)}" target="_blank" rel="noopener"><strong>${esc(p.name)}</strong><small>${esc(p.label||'Official provider')}</small></a>`).join('')}</section>`).join('')}
function choose(which,city){S.selected[which]=city;const i=$(`${which}-input`);i.value=city.label;i.dataset.cityKey=city.key;i.classList.remove('invalid');$(`${which}-error`).textContent='';close(which)}
function clear(which){S.selected[which]=null;delete $(`${which}-input`).dataset.cityKey}
function suggestions(which,q=''){q=norm(q);const list=$(`${which}-list`),items=S.cities.filter(c=>!q||c.search.includes(q)||norm(c.city).startsWith(q)).sort((a,b)=>(norm(a.city).startsWith(q)?0:1)-(norm(b.city).startsWith(q)?0:1)||b.total-a.total||a.city.localeCompare(b.city)).slice(0,15);list.innerHTML=items.length?items.map((c,i)=>`<button type="button" class="combo-option ${i?'':'active'}" data-key="${esc(c.key)}"><span><strong>${esc(c.city)}</strong><small>${esc(c.country||'Country not recorded')}</small></span><em>${c.total} records</em></button>`).join(''):'<div class="combo-empty">No matching Backroom city.</div>';list.querySelectorAll('.combo-option').forEach(b=>{b.onmousedown=e=>e.preventDefault();b.onclick=()=>choose(which,S.byCity.get(b.dataset.key))})}
function open(which,all=false){suggestions(which,all?'':$(`${which}-input`).value);$(`${which}-list`).classList.remove('hidden');$(`${which}-input`).setAttribute('aria-expanded','true')}
function close(which){$(`${which}-list`).classList.add('hidden');$(`${which}-input`).setAttribute('aria-expanded','false')}
function validate(which,show=true){const i=$(`${which}-input`),s=S.selected[which];if(s&&i.dataset.cityKey===s.key&&norm(i.value)===norm(s.label))return s;const q=norm(i.value),exact=S.cities.find(c=>norm(c.label)===q)||(()=>{const a=S.cities.filter(c=>norm(c.city)===q);return a.length===1?a[0]:null})();if(exact){choose(which,exact);return exact}clear(which);if(show){i.classList.add('invalid');$(`${which}-error`).textContent='Choose a city from the Backroom list.'}return null}
function bindCombo(which){const i=$(`${which}-input`),toggle=document.querySelector(`#${which}-combo .combo-toggle`);i.onfocus=()=>open(which);i.oninput=()=>{clear(which);i.classList.remove('invalid');$(`${which}-error`).textContent='';open(which)};i.onkeydown=e=>{const list=$(`${which}-list`),items=[...list.querySelectorAll('.combo-option')],active=items.findIndex(x=>x.classList.contains('active'));if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();if(list.classList.contains('hidden'))open(which);else{const n=Math.max(0,Math.min(items.length-1,active+(e.key==='ArrowDown'?1:-1)));items.forEach(x=>x.classList.remove('active'));items[n]?.classList.add('active');items[n]?.scrollIntoView({block:'nearest'})}}else if(e.key==='Enter'){e.preventDefault();const a=list.querySelector('.combo-option.active');a?choose(which,S.byCity.get(a.dataset.key)):validate(which)}else if(e.key==='Escape')close(which)};i.onblur=()=>setTimeout(()=>{validate(which,!!i.value);close(which)},120);toggle.onclick=()=>{i.focus();open(which,true)}}
function openSite(kind,city){try{if(parent!==window&&typeof parent.openHeatmapRecordResults==='function'){parent.openHeatmapRecordResults({city:city.city,country:city.country,mode:kind==='events'?'events':'venues',category:'all'});return}}catch(_){}top.location.href=kind==='events'?'./#calendar':'./#venues'}
function search(){const a=validate('from'),b=validate('to'),dv=$('travel-date').value;if(!a||!b)return;if(a.key===b.key){$('to-input').classList.add('invalid');$('to-error').textContent='Choose a different destination.';return}if(!dv){$('open-date-picker').click();return}S.routes=options(a,b);const pc=uniq(S.routes.flatMap(r=>(r.providers||[]).map(getProvider))).length,d=km(a,b),ec=eventCount(b,dv);$('from-name').textContent=a.city;$('to-name').textContent=b.city;$('journey-meta').textContent=[new Date(dv+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',year:'numeric',month:'long',day:'numeric'}),d?`approximately ${d.toLocaleString()} km apart`:'',`${a.country||'country unknown'} to ${b.country||'country unknown'}`].filter(Boolean).join(' · ');$('mode-count').textContent=new Set(S.routes.map(r=>r.mode)).size;$('provider-count').textContent=pc;$('route-status').textContent=S.curated?'CURATED':'GUIDE';$('destination-venues').textContent=b.venueCount;$('destination-events').textContent=ec;$('destination-note').textContent=`${b.city} has ${b.venueCount} venue listing${b.venueCount===1?'':'s'} and ${ec} dated event${ec===1?'':'s'} in the selected seven-day period.`;$('open-destination-venues').onclick=()=>openSite('venues',b);$('open-destination-events').onclick=()=>openSite('events',b);renderRoutes();renderDirectory(a,b);['summary','results','provider-directory'].forEach(id=>$(id).classList.remove('hidden'));$('summary').scrollIntoView({behavior:'smooth',block:'start'})}
function bind(){bindCombo('from');bindCombo('to');$('swap').onclick=()=>{const a=S.selected.from,b=S.selected.to;b?choose('from',b):($('from-input').value='',clear('from'));a?choose('to',a):($('to-input').value='',clear('to'))};$('find-options').onclick=search;$('sort').onchange=renderRoutes;const i=$('travel-date'),now=new Date,iso=new Date(now-now.getTimezoneOffset()*60000).toISOString().slice(0,10);i.min=i.value=iso;const picker=()=>{try{i.showPicker?i.showPicker():(i.focus(),i.click())}catch(_){i.focus()}};$('open-date-picker').onclick=picker;i.onclick=picker;document.addEventListener('click',e=>['from','to'].forEach(w=>!e.target.closest(`#${w}-combo`)&&close(w)))}
async function load(){bind();$('find-options').disabled=true;try{S.providers=window.BRTravelProviders;if(!S.providers)throw Error('Transport-provider directory missing.');const stamp=Date.now(),[vr,er]=await Promise.all([fetch(`listings.json?v=${stamp}`),fetch(`events.json?v=${stamp}`)]);if(!vr.ok||!er.ok)throw Error('Backroom venue or event data could not be loaded.');[S.venues,S.events]=await Promise.all([vr.json(),er.json()]);S.venues=Array.isArray(S.venues)?S.venues:[];S.events=Array.isArray(S.events)?S.events:[];S.byId=new Map(S.venues.map(v=>[clean(v.Venue_ID),v]).filter(([id])=>id));buildCities();if(S.cities.length<2)throw Error('Not enough Backroom cities were found.');const berlin=S.cities.find(c=>norm(c.city)==='berlin')||S.cities[0],london=S.cities.find(c=>norm(c.city)==='london')||S.cities.find(c=>c.key!==berlin.key);choose('from',berlin);choose('to',london);$('load-state').classList.add('hidden');$('find-options').disabled=false}catch(e){console.error(e);$('load-state').textContent=`Travel data could not be loaded: ${e.message}`;$('load-state').style.color='#ff7b66'}}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',load):load();
})();
